spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          services-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000

feign:
  sentinel:
    enabled: true # 开启熔断