spring:
  cloud:
    gateway:
      routes:
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: haha
            - name: Vip
              args:
                param: user
                value: leifengyang
        - id: order-route
          uri: lb://services-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/?(?<s>.*),/$\{s}
        - id: product-route
          uri: lb://services-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<s>.*),/$\{s}